AuditLogs
  | where LoggedByService =~ "Core Directory"
  | where TimeGenerated > ago(60d)
  | where OperationName in ('Add service principal', 'Add application')
  | extend Actor = iff(isempty(tostring(parse_json(tostring(InitiatedBy.user)).userPrincipalName)) == true, tostring(parse_json(tostring(InitiatedBy.app)).displayName), tostring(parse_json(tostring(InitiatedBy.user)).userPrincipalName))
  | extend resource = tostring(TargetResources[0].displayName)
  | where Actor !in ("Managed Service Identity")
  | distinct  Actor, resource
