AuditLogs
| where TimeGenerated > ago(60d)
| where OperationName == "DismissUser"
| extend Actor = iff(isempty(tostring(parse_json(tostring(InitiatedBy.user)).userPrincipalName)) == true, tostring(parse_json(tostring(InitiatedBy.app)).displayName), tostring(parse_json(tostring(InitiatedBy.user)).userPrincipalName))
| extend Target =  tostring(TargetResources[0].userPrincipalName)
| project TimeGenerated, OperationName, Actor, Target
