//Require remediation for risky users
//https://learn.microsoft.com/en-us/entra/identity/conditional-access/policy-risk-based-user
let risklevel = pack_array("high");
let riskeventsid = SigninLogs
    | where RiskLevelAggregated in(risklevel)
    | distinct OriginalRequestId;
let remediated = SigninLogs
    | where RiskState !in("none")
    | where OriginalRequestId in(riskeventsid)
    | where RiskState !in("atRisk", "none")
    | project
        OriginalRequestId,
        RemediatedDateTime = TimeGenerated,
        UserPrincipalName,
        RiskState;
let risk = SigninLogs
    | where RiskState !in("none")
    | where OriginalRequestId in(riskeventsid)
    | where RiskState in("atRisk") and RiskLevelAggregated in(risklevel)
    | where not(ResultType == 53003 and ResultDescription == "Access has been blocked due to conditional access policies.")
    | join kind = leftouter (remediated) on OriginalRequestId
    | project
        RiskDateTime = TimeGenerated,
        UserPrincipalName = tolower(UserPrincipalName),
        RemediatedDateTime,
        riskuserRiskLevelAggregated = RiskLevelAggregated,
        ResultType;
let riskusers = risk
    | distinct UserPrincipalName = tolower(UserPrincipalName);
SigninLogs
| where ResultType == 0
| where tolower(UserPrincipalName) in(riskusers)
| where AppDisplayName !in("Windows Sign In", "Microsoft Authentication Broker")
| extend ["Device trust type"] = tostring(parse_json(DeviceDetail).trustType)
| extend ["Device is compliant"] = tostring(parse_json(DeviceDetail).isCompliant)
| join kind = leftouter (risk) on UserPrincipalName
| where ((TimeGenerated <= RemediatedDateTime) or (isnull(RemediatedDateTime))) and (TimeGenerated >= RiskDateTime)
| distinct UserPrincipalName = tolower(UserPrincipalName)
