//Web-only access for guests with unmanaged devices
// https://learn.microsoft.com/en-us/entra/identity/conditional-access/policy-guests-mfa-strength
let excludeapps = pack_array("Windows Sign In","Microsoft Authentication Broker","Microsoft Account Controls V2");
SigninLogs 
| where TimeGenerated > ago(14d) and UserType == "Guest" and AppDisplayName !in (excludeapps)
| where ResultType == 0 and ClientAppUsed == 'Mobile Apps and Desktop clients'
| where AADTenantId == ResourceTenantId
| summarize Resource = make_set(ResourceDisplayName) by  UserPrincipalName, AppDisplayName
