//https://www.linkedin.com/pulse/detect-device-code-authentication-phishing-kloudynet-i0rpc/

union SigninLogs, AADNonInteractiveUserSignInLogs
| where TimeGenerated >= ago(90d) 
| where AuthenticationProtocol=="deviceCode" or AuthenticationProtocol =="authenticationTransfer"
| project TimeGenerated, UserPrincipalName,ResultType, ResultDescription,UserAgent, IPAddress, Location,AppDisplayName,ResourceDisplayName, AuthenticationProtocol, AuthenticationRequirement 
