AuditLogs
| where TimeGenerated > ago(90d)
| where OperationName == "Fraud reported - user is blocked for MFA"
| extend InitiatedBy = tostring(parse_json(tostring(InitiatedBy.user)).userPrincipalName)
| extend UserPrincipalName = tostring(TargetResources[0].userPrincipalName)
| extend targetResources=parse_json(TargetResources)
| extend targetResources=parse_json(TargetResources)
| project TimeGenerated, OperationName, InitiatedBy, UserPrincipalName, ResultReason
