name: Block Unauthorized Emails

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  email-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Scan for unauthorized email addresses
        run: |
          echo "🔍 Scanning for unauthorized emails..."

          # Extract all email-like strings (skip .git directory)
          matches=$(grep -iEroh --exclude-dir=.git "[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}" . || true)

          found=0
          for email in $matches; do
            if ! echo "$email" | grep -Eiq \
              "^chadco@microsoft\.com$|^chad\.cox@microsoft\.com$|^authenticationStrength@odata\.context$|^admin@M365x437870\.onmicrosoft\.com$|@contoso\.com$|@([A-Za-z0-9.-]+\.)?chadcolabs\.us$"; then
              echo "❌ Unauthorized email found: $email"
              found=1
            fi
          done

          if [ "$found" -eq 1 ]; then
            echo "🚫 Commit or PR contains unauthorized email addresses."
            exit 1
          else
            echo "✅ All emails are from approved sources."
          fi
